default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 16 %>
  username: furry-wookie

development:
  <<: *default
  database: furry-wookie_development

test:
  <<: *default
  database: furry-wookie_test

production:
  <<: *default
  database: furry-wookie_production
  username: furry-wookie
  password: <%= ENV['FURRY-WOOKIE_DATABASE_PASSWORD'] %>
